CREATE CONSTRAINT person_id IF NOT EXISTS FOR (p:Person) REQUIRE p.person_id IS UNIQUE;
CREATE CONSTRAINT name_id IF NOT EXISTS FOR (n:NameVariant) REQUIRE n.name_id IS UNIQUE;
CREATE CONSTRAINT source_id IF NOT EXISTS FOR (s:Source) REQUIRE s.source_id IS UNIQUE;
CREATE CONSTRAINT assertion_id IF NOT EXISTS FOR (a:Assertion) REQUIRE a.assertion_id IS UNIQUE;
CREATE CONSTRAINT passage_id IF NOT EXISTS FOR (p:Passage) REQUIRE p.passage IS UNIQUE;
CREATE CONSTRAINT identity_option_id IF NOT EXISTS FOR (i:IdentityOption) REQUIRE i.option_id IS UNIQUE;
LOAD CSV WITH HEADERS FROM "file:///person_nodes.csv" AS row MERGE (p:Person {person_id: row.person_id}) SET p += row, p.nt_ref_count = toInteger(row.nt_ref_count), p.ot_ref_count = toInteger(row.ot_ref_count), p.bible_ref_count = toInteger(row.bible_ref_count), p.testament = row.testament
LOAD CSV WITH HEADERS FROM "file:///name_nodes.csv" AS row MATCH (p:Person {person_id: row.person_id}) MERGE (n:NameVariant {name_id: row.name_id}) SET n += row MERGE (p)-[:HAS_NAME]->(n);
LOAD CSV WITH HEADERS FROM "file:///evidence_nodes.csv" AS row MERGE (s:Source {source_id: row.source_id}) SET s += row;
LOAD CSV WITH HEADERS FROM "file:///assertion_nodes.csv" AS row MERGE (a:Assertion {assertion_id: row.assertion_id}) SET a += row;
LOAD CSV WITH HEADERS FROM "file:///identity_option_nodes.csv" AS row MATCH (p:Person {person_id: row.person_id}) MERGE (i:IdentityOption {option_id: row.option_id}) SET i.identity_key = row.identity_key, i.status = row.status, i.identity_scope = row.identity_scope, i.merge_group_id = CASE row.merge_group_id WHEN "" THEN null ELSE row.merge_group_id END, i.merge_target_person_id = CASE row.merge_target_person_id WHEN "" THEN null ELSE row.merge_target_person_id END, i.display_label = CASE row.display_label WHEN "" THEN null ELSE row.display_label END, i.rationale = row.rationale, i.editor_note = row.editor_note MERGE (p)-[:HAS_IDENTITY_OPTION]->(i);
LOAD CSV WITH HEADERS FROM "file:///passage_nodes.csv" AS row MERGE (p:Passage {passage: row.passage}) SET p.passage = row.passage, p.testament = row.testament
LOAD CSV WITH HEADERS FROM "file:///mention_edges.csv" AS row MATCH (person:Person {person_id: row.person_id}), (psg:Passage {passage: row.passage}) MERGE (person)-[r:MENTIONED_IN]->(psg) SET r.mention_id = row.mention_id, r.source_id = row.source_id, r.status = row.status;
LOAD CSV WITH HEADERS FROM "file:///assertion_nodes.csv" AS row MATCH (s:Person {person_id: row.subject_person_id}), (o:Person {person_id: row.object_person_id}), (a:Assertion {assertion_id: row.assertion_id}) MERGE (a)-[:SUBJECT]->(s) MERGE (a)-[:OBJECT]->(o);
LOAD CSV WITH HEADERS FROM "file:///assertion_evidence.csv" AS row MATCH (a:Assertion {assertion_id: row.assertion_id}), (src:Source {source_id: row.source_id}), (psg:Passage {passage: row.passage}) MERGE (a)-[r1:SUPPORTED_BY]->(src) SET r1.evidence_level = row.evidence_level, r1.certainty = CASE row.certainty WHEN "" THEN null ELSE toFloat(row.certainty) END, r1.note = row.note MERGE (a)-[r2:SUPPORTED_BY]->(psg) SET r2.evidence_level = row.evidence_level, r2.certainty = CASE row.certainty WHEN "" THEN null ELSE toFloat(row.certainty) END, r2.note = row.note;
